name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Testing
        run: deno test

      - name: Build
        run: deno task build:node ${{ github.ref }}

      - name: Publish to registry.npmjs.com
        run: |
          cd ./npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - uses: actions/github-script@v6
        id: changelog
        with:
          result-encoding: string
          script: |
            const { stdout } = await exec.getExecOutput('git', ['cliff', '-l', '--strip', 'header'])
            return stdout

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ steps.changelog.outputs.result }}
