name: Release

on:
  release:
    types:
      - released
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  draft:
    name: Create draft release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - uses: actions/github-script@v6
        id: changelog
        with:
          result-encoding: string
          script: |
            const { stdout } = await exec.getExecOutput('git', ['cliff', '-l', '--strip', 'header'])
            return stdout

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ steps.changelog.outputs.result }}

  publish:
    name: Publish to JSR
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish (dry-run)
        run: deno publish --dry-run

      - name: Publish
        run: deno publish
